package br.pucrio.inf.learn.structlearning.discriminative.algorithm;

import br.pucrio.inf.learn.structlearning.discriminative.data.ExampleInput;
import br.pucrio.inf.learn.structlearning.discriminative.data.ExampleOutput;

/**
 * Interface for a structured learning algorithm.
 * 
 * @author eraldof
 * 
 */
public interface OnlineStructuredAlgorithm extends StructuredAlgorithm {

	/**
	 * Update the currect model using the given correct output and the predicted
	 * output for this example. Attention: the given <code>predicted</code> is
	 * only a placeholder to store the predicted structure, i.e., the prediction
	 * will be done inside this method.
	 * 
	 * @param input
	 *            the input structure.
	 * @param output
	 *            the correct output structured.
	 * @param predicted
	 *            a place holder for the predicted structured.
	 * @return the loss function value for the given correct output and the
	 *         predicted output using the current weight vector (before the
	 *         possible update generated by the given example).
	 */
	public double train(ExampleInput input, ExampleOutput output,
			ExampleOutput predicted);

}
